


PAD = u"_PAD"
PAD_POS = u"_PAD_POS"
PAD_TYPE = u"_<PAD>"
PAD_CHAR = u"_PAD_CHAR"
ROOT = u"_ROOT"
ROOT_POS = u"_ROOT_POS"
ROOT_TYPE = u"_<ROOT>"
# NB : those two following variables were designed for ROOT that have no meaning in terms of parsing
ROOT_HEADS_INDEX = -1
END_HEADS_INDEX = -1
ROOT_CHAR = u"_ROOT_CHAR"
END = u"_END"
END_POS = u"_END_POS"
END_TYPE = u"_<END>"
END_CHAR = u"_END_CHAR"
_START_VOCAB = [PAD, ROOT, END]
CHAR_START = u"_START"

PAD_ID_LOSS_STANDART = -1
HEADS_FOR_SPECIAL_TOKEN_PARSING = -1

NULL_STR = "[SPACE]"

NULL_STR = "[SPACE]"
NULL_STR_TO_SHOW = "_"

#MASK_BERT = "<mask>" #"[MASK]"
##SEP_BERT = "</s>" #"[SEP]"
#CLS_BERT = "<s>"

#TOKEN_BPE_BERT_START = CLS_BERT
#TOKEN_BPE_BERT_SEP = SEP_BERT

PADING_SYMBOLS = ['<s>NOTUSED', PAD,"<pad>", PAD_POS, PAD_TYPE]

SPECIAL_TOKEN_LS = [ROOT_CHAR, END_CHAR, ROOT, ROOT_POS, END_POS, END, PAD_ID_LOSS_STANDART, ROOT_TYPE, END_TYPE, HEADS_FOR_SPECIAL_TOKEN_PARSING]